Ong5 30 formulario creacion edicion slides
alkemyTech/React-SXXI-T3 pull request #10
Opened 2022-11-02 18:14 UTC by junx2000

SlidesForm.js - Se crea/actualiza el componente SlidesForm
FormStyles.css - Se actualiza para que todos contemos con el mismo estilo de Form.
slideFormServices.js - Servicio que hace las request referidas a Slides a la API.
BackofficeRoutes.js - Se actualiza con la ruta al componente SlidesFrom

2022-11-02 22:26 UTC, junx2000 commented
Queda pendiente el envio de la imagen en el request

2022-11-03 15:07 UTC, pcuneo requested changes

2022-11-03 15:07 UTC, pcuneo commented on src/Components/Slides/SlidesForm.js
> +        fileReader.readAsDataURL(file);
El setFieldValue actualiza el valor luego de ejecutar onSubmitService , por lo tanto nunca se esta enviando la imagen.

onloadend debería ser onload

Por el asincronismo de FileReader es mas conveniente llamarlo en el handler del input de la imagen, y no en el onsubmit, de forma que cuando se llame al onsubmit ya este seteado imageBase64

2022-11-04 18:54 UTC, pcuneo approved these changes
Aprobada

2022-11-04 19:23 UTC, merged