Feature/formulario edicion creacion miembros ong 35
alkemyTech/React-SXXI-T3 pull request #12
Opened 2022-11-03 15:10 UTC by GabrielVodopivec

Formulario reutilizable de Actualización y Creación de Miembros para casos donde reciba por parametro en la URL un ID de miembro a modificar o donde se requiera crear un miembro nuevo.

2022-11-03 15:45 UTC, pcuneo requested changes
Revisar los estilos en los errores y el boton, la idea es que los colores en backoffice sean distintos o falto aplicar el estilo al boton?

2022-11-03 15:45 UTC, pcuneo commented on src/Components/Members/MembersForm.jsx
> +
El use effect no esta usando setSubmitting, ese necesario?
Para la carga inicial es mejor utilizar un state dedicado y no utilizar el de formik.

```
const [isFetching, setIsFetching] = useState(); // para el use effect
const isLoading = isFecthing || isSubmitting; // isLoading para activar la animacion
```

2022-11-03 15:45 UTC, pcuneo commented on src/Components/Members/MembersForm.jsx
> +        setSubmitting(false)
En general es preferible dejas que formik maneje el setSubmitting.

2022-11-03 16:23 UTC, GabrielVodopivec commented on src/Components/Members/MembersForm.jsx
> +
![localhost_3000_backoffice_miembros_crear](https://user-images.githubusercontent.com/86635577/199775944-64163df8-9f4d-48a3-ac7d-cc9df1b4f795.png)
![localhost_3000_backoffice_miembros_editar_879](https://user-images.githubusercontent.com/86635577/199775963-2a51a54a-0cd5-48d0-9da4-29e93e0bd27d.png)

En cuanto a los estilos debe haber algun problema de actualización de estilos generales porque todos los formularios debería mantener un mismo estilo de colores y formas

El setSubmmiting del useEffect tengo que eliminarlo, era parte de una implementación que no funcionó bien y ahora la lógica no lo necesita.

2022-11-03 16:25 UTC, GabrielVodopivec commented on src/Components/Members/MembersForm.jsx
> +        setSubmitting(false)
Lo voy a volver a revisar, pero estoy controlando el isSubmmiting de forma imperativa porque el estado me quedaba en true, formik no actualizaba el estado.

2022-11-03 17:20 UTC, GabrielVodopivec commented
En el último commit modifiqué la logica del useEffect, creo que había malinterpretado la recomendación

2022-11-03 17:34 UTC, GabrielVodopivec commented on src/Components/Members/MembersForm.jsx
> +        setSubmitting(false)
agrego la docuamentación en la que me basé para implementarlo de ésta manera
https://formik.org/docs/api/formik#setsubmitting-issubmitting-boolean--void

2022-11-04 18:59 UTC, pcuneo approved these changes

2022-11-04 19:39 UTC, merged