Feature/formulario creacion edicion categorias ong 28
alkemyTech/React-SXXI-T3 pull request #2
Opened 2022-10-28 17:41 UTC by GabrielVodopivec

Formulario de Actualización y Creación de Categorías reutilizable para casos donde reciba una categoría existente a modificar o donde se requiera crear una categoría nueva.

2022-10-28 18:20 UTC, milandre commented on src/Components/Categories/CategoriesForm.js
> +        // if (category) {
Acá les dejo un comentario: 
No es de buenas prácticas dejar comentado código cuando hacen un PR de una feature que consideren que está completa.

2022-10-28 18:22 UTC, milandre commented on src/Components/Categories/CategoriesForm.js
> +        console.log(values);
Acá les dejo un comentario:
No es de buenas prácticas dejar console.log cuando hacen un PR de una feature que consideren que está completa.

2022-10-28 18:27 UTC, milandre submitted a review, later dismissed
Para aprobar esta historia de usuario, falta que cumplan los criterios de aceptación, entre ellos que ya tenga integrado la parte de los endpoints.

2022-10-28 18:28 UTC, GabrielVodopivec commented on src/Components/Categories/CategoriesForm.js
> +        console.log(values);
Dale! buenisimo! ahora cambio los comentarios por alguna lógica temporal que simule la definitiva. Gracias!

2022-10-28 18:44 UTC, GabrielVodopivec commented on src/Components/Categories/CategoriesForm.js
> +        console.log(values);
Esto del console.log lo implente así por error. Tengo otra tarea que pide hacerlo de esta manera temporalmente, me confundí. Ya estoy haciendo las correcciones

2022-10-28 19:51 UTC, GabrielVodopivec commented
En esta útlima actualización el formulario está utilizando los endpoints correspondientes en cada caso, actuando según como se resuelva la solicitud. Eliminé comentarios y los console.log.
Por último, aclaro que no se esta enviando el campo imagen dado que el servidor responde con error en caso de incluirla en la solicitud.

2022-10-28 20:22 UTC, pcuneo commented on src/Components/Categories/CategoriesForm.js
> +                .put(`https://ongapi.alkemy.org/api/categories/${category.id}`, {
Estaría mejor utilizar configuración de ambiente para la url base de api.
Mejor aun seria crear un instancia de axios para no tener que pasar siempre baseURL.

https://axios-http.com/docs/instance 

eso permite pasa únicamente el recurso relativo y no tener que escribir siempre `https://ongapi.alkemy.org/api` 
```
import api from "../api"
// ....
api.put(`/categories/${category.id}`, {  
// ...
```

2022-10-28 20:50 UTC, GabrielVodopivec commented on src/Components/Categories/CategoriesForm.js
> +                .put(`https://ongapi.alkemy.org/api/categories/${category.id}`, {
Hola Paulo! muy buena recomendación, no la conocía, ahora mismo me pongo con la instanciación de axios! Muchas gracias!

2022-10-29 14:50 UTC, pcuneo requested changes

2022-10-29 14:50 UTC, pcuneo commented on src/Services/apiONG/index.js
> +export const apiBaseURL = axios.create({
apiBaseUrl es un nombre raro, baseURL tiene que ver con la forma en esta configurado y no con la responsabilidad que tiene el objeto/instancia de axios, mejor algo tipo "apiong","apiONG" , "ongAPI", "ongService", "ongClient" o incluso "ong".

Generalmente es preferible que los nombres hagan referencia a **"que es?"** el objeto, servicio, etc. 
Ya que **"como lo hace? Como lo logra?"** siempre esta determinado por como esta configurado/codeado.

Que es? es una instancia de axios para consumir la api de ong.
Que es axios? axios es un cliente de http.
Es decir este objeto es un cliente para consumir la api http de la ong. El nombre deberia hacer referencia a eso.

2022-10-29 17:52 UTC, GabrielVodopivec commented on src/Services/apiONG/index.js
> +export const apiBaseURL = axios.create({
Clarísimo! voy a empezar a usar este criterio para definir los nombres de variables e instancias según conrresponda. Ahora lo corrijo, muchas gracias!

2022-10-29 19:27 UTC, pcuneo approved these changes

2022-10-29 20:21 UTC, pcuneo requested changes
Perdón que te estoy pasando mas revisiones, pensé que solo faltaba los axios instance. 
Pero encontré unos detalles. 
Ademas por lo que veo falta configurar correctamente el router en App.js, pero puede hacerse en otra historia (en la nueva version de router se usar `element` en Route) esto ultimo puede ser parte de otra historia

2022-10-29 20:21 UTC, pcuneo commented on src/Components/Categories/CategoriesForm.js
> +                        setFieldTouched('description', 'description is a required field')
setFieldTouched espera un booleano como segundo parametro.

https://formik.org/docs/api/formik#setfieldtouched-field-string-istouched-boolean-shouldvalidate-boolean--void

2022-10-29 20:21 UTC, pcuneo commented on src/Components/Categories/CategoriesForm.js
> +        Yup.object().shape({
Poner los mensajes de requerido en español

2022-10-29 20:21 UTC, pcuneo commented on src/Components/Categories/CategoriesForm.js
> +                <button className="submit-btn" type="submit">Send</button>
Mostremos texto en español, ya los usuarios son de habla hispana

2022-10-29 20:21 UTC, pcuneo commented on src/Services/categoryFormServices/index.js
> +                const errorMessage = (
queda mejor la sintaxis con chaining operator

``` error.response
                    && error.response.data
                    && error.response.data.message
//
 error.response?.data?.message  ||   error.message                 
                    
```

2022-10-29 20:21 UTC, pcuneo commented on src/Services/categoryFormServices/index.js
> +                    && error.response.data
Queda mas lindo con chaining operator `?.`

2022-10-29 20:32 UTC, GabrielVodopivec commented on src/Components/Categories/CategoriesForm.js
> +                        setFieldTouched('description', 'description is a required field')
Había revisado la documentación, pero como esos parametros eran opcionales y venian por defecto como los necesitaba no los agregue.

2022-10-29 20:33 UTC, GabrielVodopivec commented on src/Components/Categories/CategoriesForm.js
> +        Yup.object().shape({
Estaba usando inglés como idioma para todo el componente, cambio Todo el texto a español entonces? Incluidas etiquetas de inputs y titulos?

2022-10-29 20:35 UTC, GabrielVodopivec commented on src/Services/categoryFormServices/index.js
> +                    && error.response.data
Totalmente, ahora lo modifico!

2022-10-29 20:36 UTC, GabrielVodopivec commented on src/Components/Categories/CategoriesForm.js
> +                <button className="submit-btn" type="submit">Send</button>
Con este comentario se responde la pregunta que hice arriba

2022-10-29 20:39 UTC, GabrielVodopivec commented on src/Components/Categories/CategoriesForm.js
> +                        setFieldTouched('description', 'description is a required field')
Y respecto a la raiz del projecto, entre hoy y mañana nos vamos a reunir para modificarlo y adaptarlo a las nuevas versiones y requerimentos del proyecto.

2022-10-31 11:47 UTC, pcuneo commented on src/Components/Categories/CategoriesForm.js
> +        Yup.object().shape({
Me refería a los textos y mensajes de error.

2022-10-31 18:43 UTC, pcuneo approved these changes

2022-10-31 19:54 UTC, merged