Ong5 39
alkemyTech/React-SXXI-T3 pull request #22
Opened 2022-11-08 21:51 UTC by GabrielVodopivec

Screen de datos de la organización. En esta vista se pueden ver los datos de la organización que se muestran publicamente      y contiene un link a un formulario de edición de la misma.

2022-11-08 23:13 UTC, pcuneo requested changes

2022-11-08 23:13 UTC, pcuneo commented on src/Components/Organization/OrganizationScreen/organizationScreen.module.css
> +}
Responsiveness: falta el estilo cuando se ve en escritorio.

![image](https://user-images.githubusercontent.com/14055490/200696031-cefbd695-c1b6-44e4-a904-24796dba7142.png)

2022-11-09 01:13 UTC, GabrielVodopivec commented
Versión actual del screen de datos de la organización
Escritorio/Mobile
![Screen de datos de la organización](https://user-images.githubusercontent.com/86635577/200711774-fb586416-3203-4a61-afe4-bbb794cc2d8e.png)

2022-11-09 01:15 UTC, pcuneo approved these changes

2022-11-09 13:08 UTC, merged