ONG5-57 y ONG5-58
alkemyTech/React-SXXI-T3 pull request #30
Opened 2022-11-10 20:33 UTC by junx2000

2022-11-11 03:10 UTC, pcuneo requested changes

2022-11-11 03:10 UTC, pcuneo commented on src/Components/Activities/ActivitiesList.jsx
> +                    id={element.id}
Cuando pruebo la pagina salta:
![image](https://user-images.githubusercontent.com/14055490/201254604-21126894-2098-4157-985c-cdf53d668392.png)

2022-11-13 15:42 UTC, junx2000 commented on src/Components/Activities/ActivitiesList.jsx
> +                    id={element.id}
Ya arreglé el warning

2022-11-15 03:24 UTC, pcuneo approved these changes

2022-11-15 22:25 UTC, merged