Ong5 38
alkemyTech/React-SXXI-T3 pull request #31
Opened 2022-11-10 23:15 UTC by elcharlybeto

NewsletterForm.jsx/css - Fromulario de subscripción a newsletter para ubicar en footer (dentro de carpeta src/Components/Footer/NewsletterForm)

2022-11-11 03:12 UTC, pcuneo requested changes
Salta este error al correr la app.

![image](https://user-images.githubusercontent.com/14055490/201254846-0e267766-0a89-4555-82ac-6a9c4dadbdcf.png)

2022-11-11 03:25 UTC, pcuneo requested changes

2022-11-11 03:25 UTC, pcuneo commented on src/Components/Footer/NewsletterForm/NewsletterForm.jsx
> +
Tener en cuenta que en este caso el valor inicial de isSubscribed tiene mas sentido que sea true.
Porque si no esta subscrito no se muestra nada. En cambio como esta ahora inicializado a false, si esta subscrito va a pintar el componente y luego lo va a despintar, si el usuario lo ve va a dar la impresión que la app es inestable.
   
De todas formas en este caso el useEffect/useState esta medio raro por que no esta sincronizando nada. Es decir, isSubscribe se puede tomar directo del localstorage, por lo que agregar un state para ello no tiene mucho sentido. Y de todas formas se esta consultando el localstorage cada vez que se pinta el componente.
Es decir, hay 2 alternativas:
```
// 1
const isSubscribed = Boolean(localStorage.getItem("newsletter")); 
// se corre cada vez que pinta el componente
```

```
// 2
  const [isSubscribed, setIsSubscribed] = useState(true);
  ...
  useEffect(() => {
     setIsSubscribed(Boolean(localStorage.getItem("newsletter")));
  }, []);
  // se corre la primera vez que se pinta el componente
```
Para lo que pide el tp la primera es mas simple.

2022-11-11 03:27 UTC, pcuneo commented
@elcharlybeto por las dudas no hay problema con trabajar en 2 historias el mismo tiempo, pero hacer que las 2 branch salgan de develop

2022-11-11 13:30 UTC, elcharlybeto commented on src/Components/Footer/NewsletterForm/NewsletterForm.jsx
> +
Claro, lo pensé hacer con la const como el primer caso, pero quería forzar el refresh (en caso necesario) porque si está subscripto yo muestro el formulario igualmente pero lo cambio a "desubscribir", vos decís que no lo muestre entonces? Yo le quise dar esa opción porque no ví mecanismo en la página hasta ahora que te dé la posibilidad de cancelar la subscripción al newsletter.

2022-11-11 13:33 UTC, elcharlybeto commented on src/Components/Footer/NewsletterForm/NewsletterForm.jsx
> +
Con respecto a las rutas, te pido disculpas, estaba desactualizada la rama development al crear esta nueva. Eso ya lo corregí, ahora te pido que cuando puedas me des el feedback de lo que te pregunté y así lo corrijo en caso de ser necesario. Gracias, Paulo!!!

2022-11-11 18:30 UTC, pcuneo commented on src/Components/Footer/NewsletterForm/NewsletterForm.jsx
> +
Ok, es que el jira no habla de desuscribir. Por eso mi comentario. Lo que suele usar es desuscribirte desde el newsletter(desde el mail).
Fijate seria medio raro que yo pueda ingresar un mail y desuscribir ese email. Es decir, puedo desuscribir a otros?
Vayamos por lo mas simple.

2022-11-12 14:57 UTC, elcharlybeto commented on src/Components/Footer/NewsletterForm/NewsletterForm.jsx
> +
Genial, Paulo!!! Ahora lo corrijo, muchas gracias!!!

2022-11-12 16:36 UTC, elcharlybeto commented
Listo @pcuneo :)

2022-11-12 23:45 UTC, pcuneo approved these changes

2022-11-13 00:06 UTC, merged