agrego formulario login y assets
alkemyTech/React-SXXI-T3 pull request #4
Opened 2022-10-31 15:12 UTC by elcharlybeto

mi primer pull request, téngame piedad, please, jaja

2022-10-31 20:05 UTC, pcuneo requested changes
Podes agregarlo al router para que se pueda probar?

2022-10-31 21:23 UTC, elcharlybeto commented
Ya agregué la ruta, Paulo, traté de copiar los últimos cambios que se mergearon de la actualización de las rutas y la versión de react, igual te genera un conflicto porque hay que incluir el componente <Login/> en la ruta para poder probarla.

2022-11-01 13:06 UTC, pcuneo approved these changes

2022-11-01 13:07 UTC, pcuneo commented
PR aprobada, @elcharlybeto resolve los conflictos y dale merge cuando quieras

2022-11-01 13:52 UTC, merged

2022-11-01 13:52 UTC, elcharlybeto commented
Listo, Paulo, gracias!!!