ONG5-100
alkemyTech/React-SXXI-T3 pull request #63
Opened 2022-12-06 02:07 UTC by naara1993

link de la tarea https://alkemy-labs.atlassian.net/jira/software/c/projects/ONG5/boards/422?modal=detail&selectedIssue=ONG5-100   
Ultima modificacion, en el detalle de novedades se muestra comentarios  y se  implementa Skeleton para mostrar los mismos.

2022-12-06 18:47 UTC, rodrigotonso requested changes

2022-12-06 18:47 UTC, rodrigotonso commented on src/Components/Comments/CommentsDetails.jsx
> +    }, 5000);
Por que u n loading con timeout ¿?

2022-12-06 18:47 UTC, rodrigotonso commented on src/Components/Comments/CommentsDetails.jsx
> +        const user = response.data.data;
El user no lo estamos guardando en localstorage o en redux todavía??

2022-12-06 18:47 UTC, rodrigotonso commented on src/Components/Comments/CommentsDetails.jsx
> +      if (userId.includes(Number(comment[i].user_id))) {
if vacio ¿?

2022-12-06 18:47 UTC, rodrigotonso commented on src/Components/Comments/CommentsDetails.jsx
> +  for (let i = 0; i < comment.length; i++) {
Talvez se puede usar .map() o .foreach()

2022-12-06 18:47 UTC, rodrigotonso commented on src/Components/Comments/CommentsDetails.jsx
> +        if(userId.includes(userAux)){
if vacio ¿?

2022-12-06 18:47 UTC, rodrigotonso commented on src/Components/Comments/CommentsDetails.jsx
> +          if(userAux!==undefined){
muy anidado ya, podemos buscar alternativa

2022-12-06 18:47 UTC, rodrigotonso commented on src/Components/Comments/CommentsDetails.jsx
> +        </div>
El encabezado se usa tanto aca como en el else de este if
Podríamos sacarlo afuera y hacer el if un poco despues

2022-12-06 18:47 UTC, rodrigotonso commented on src/Components/Comments/CommentsDetails.jsx
> +            return (
Solo propuesta de mejora talvez sacar el skeleton como componente afuera, es mucho código que ensucia

2022-12-06 22:00 UTC, naara1993 commented on src/Components/Comments/CommentsDetails.jsx
> +    }, 5000);
Porque inicialmente a loading lo pongo en  true,para asi de esa forma cuando la pagina se muestre aparezca que se esta cargando los comentarios con Skeleton, luego de unos segundos con timeout cambio el valor de loading a false para que muestre los comentarios.

2022-12-06 22:13 UTC, naara1993 commented on src/Components/Comments/CommentsDetails.jsx
> +        const user = response.data.data;
Queria traer los datos de los usuarios para asi mostrar la foto y el nombre en el comentario que realizo. Por eso me parecio mas conveniente traer los datos de los usuarios.

2022-12-06 22:42 UTC, naara1993 commented
Realizo las modificaciones,  en el detalle de novedades muestro la lista de comentarios con sus datos, inicialmente al mostrar la pagina loading esta en false, para asi dar ese efecto que cargan los comentarios con Skeleton, luego con timeout cambia su estado y se cargan los comentarios con sus datos.

2022-12-07 18:48 UTC, rodrigotonso approved these changes

2022-12-07 19:02 UTC, merged