Ong5 31 formulario creacion edicion testimonios
alkemyTech/React-SXXI-T3 pull request #9
Opened 2022-11-02 17:42 UTC by junx2000

TestimonialsForm.js - Se crea/actualiza el componente TestimonialsForm
FormStyles.css - Se actualiza para que todos contemos con el mismo estilo de Form.
testimonialFormServices.js - Servicio que hace las request referidas a Testimonios a la API.
BackofficeRoutes.js - Se actualiza con la ruta al componente TestimonialsForm

2022-11-02 22:25 UTC, junx2000 commented
Queda pendiente el envio de la imagen en el request

2022-11-03 15:05 UTC, pcuneo requested changes
Quedaron las los endpoints,

2022-11-03 15:05 UTC, pcuneo commented on src/Services/testimonialFormServices.js
> +            .put(`/categories/${id}`, {
esta haciendo put a "/categories" deberia ser "/testimonials"

2022-11-03 15:05 UTC, pcuneo commented on src/Services/testimonialFormServices.js
> +            .post(`/testimonial`, body)
Debería ser testimonials, plural 
https://ongapi.alkemy.org/api/docs#/Testimonial

2022-11-03 15:05 UTC, pcuneo commented on src/Components/Testimonials/TestimonialsForm.js
> +
Limpiar imports, no se usa useState, useEffect

2022-11-03 15:05 UTC, pcuneo commented on src/Components/Testimonials/TestimonialsForm.js
> +        };
El setFieldValue actualiza el valor luego de ejecutar onSubmitService , por lo tanto nunca se esta enviando la imagen.

onloadend debería ser onload

Por el asincronismo de FileReader es mas conveniente llamarlo en el handler del input de la imagen, y no en el onsubmit, de forma que cuando se llame al onsubmit ya este seteado `imageBase64`

2022-11-04 18:52 UTC, pcuneo approved these changes

2022-11-04 19:29 UTC, merged